<a href="https://colab.research.google.com/github/Ramandeep-Singh17/DLusingPyTorch/blob/main/1_tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧠 Tensors in PyTorch

---

## 🔹 What is a Tensor?

Tensor is a **data structure used to store numerical data in Deep Learning**.

In simple words:
> Tensor = Multi-dimensional array

It can store:
- Numbers
- Vectors
- Images
- Videos
- Model weights
- Predictions

PyTorch ka main building block = Tensor

---

## 🔹 Why Do We Use Tensors?

We use tensors because:

- Neural networks work only on numbers
- GPU computation needs structured numeric data
- Matrix operations (multiplication, addition) need multi-dimensional arrays
- Backpropagation needs tensors to compute gradients

Without tensors:
- No forward pass
- No loss calculation
- No training

---

## 🔹 Where Are Tensors Used?

Tensors are used in:

- Images (Computer Vision)
- Text (NLP)
- Audio processing
- Videos
- Model parameters (weights)
- Loss values
- Gradients

Every input and output in Deep Learning = Tensor

---

## 🔹 When Do We Use Tensors?

We use tensors:

- While giving input to model
- During forward pass
- While calculating loss
- During backpropagation
- During prediction

---

## 🔹 How Does Tensor Represent Data?

Tensor stores data based on **dimensions (axes)**.

---

# 📊 Types of Tensors (Based on Dimensions)

---

## 0️⃣ 0D Tensor (Scalar)

- Single number
- No direction

Example:
Loss value

If:
Prediction = 8  
Target = 10  
Loss = 2  

That 2 is a scalar (0D tensor)

✔ Loss is always scalar

---

## 1️⃣ 1D Tensor (Vector)

- One direction
- Like a list or array

Example:
[2, 5, 7, 9]

### 📌 Example: Word Embedding

Embedding means:
> Converting words into numbers (vectors)

Example:
"king"  → [0.25, 0.71, 0.90]  
"queen" → [0.27, 0.69, 0.88]  

Similar words → similar vectors

Used in:
- NLP
- Chatbots
- LLMs

Embedding = 1D tensor

---

## 2️⃣ 2D Tensor (Matrix)

- Two directions (rows, columns)

Example:
[[1, 2, 3],
 [4, 5, 6]]

### 📌 Example: Grayscale Image

Grayscale image has:
- Height
- Width

Shape:
[Height, Width]

Example:
[28, 28]

---

## 3️⃣ 3D Tensor

- Three directions

### 📌 Example: RGB Image

RGB image has:
- Channels (3)
- Height
- Width

Shape:
[Channels, Height, Width]

Example:
[3, 224, 224]

---

## 4️⃣ 4D Tensor

- Four directions

### 📌 Example: Batch of RGB Images

During training, model takes multiple images together.

Shape:
[Batch_size, Channels, Height, Width]

Example:
[32, 3, 224, 224]

Meaning:
32 images in one batch

---

## 5️⃣ 5D Tensor

- Five directions

### 📌 Example: Video

Video = Sequence of images

Shape:
[Batch_size, Time, Channels, Height, Width]

Example:
[8, 10, 3, 224, 224]

Meaning:
8 videos  
Each video has 10 frames  

---

# 🔥 Important Points

- Tensor = Multi-dimensional array
- PyTorch uses tensors instead of NumPy arrays
- Tensors can run on GPU
- Gradients are also tensors
- Everything in Deep Learning is stored as tensor

---

# 🎯 Quick Summary

0D → Scalar (Loss)  
1D → Vector (Embedding)  
2D → Matrix (Grayscale image)  
3D → RGB image  
4D → Batch of images  
5D → Video  

---


# 🚀 Why We Use Tensors in PyTorch

---

## 🔹 Why Do We Use Tensors?

Tensors are used because they are:

- Very fast for mathematical calculations
- Able to represent complex data (images, audio, video, text)
- Optimized for GPU / TPU computation

In Deep Learning:
Everything = Numbers  
Numbers are stored in = Tensors  

---

## 1️⃣ Mathematical Operations

Tensors allow fast operations like:

- Addition
- Subtraction
- Multiplication
- Matrix multiplication
- Dot product
- Activation functions

Neural networks are full of matrix operations.  
Without tensors → no neural network.

Example:
Forward pass = Matrix multiplication between input & weights.

---

## 2️⃣ Representation of Real-World Data

Real-world data can be represented easily using tensors:

- Image → 3D tensor
- Batch of images → 4D tensor
- Video → 5D tensor
- Text → 1D tensor (embeddings)
- Audio → 2D / 3D tensor

Tensor helps convert real-world data into numbers so model can understand it.

---

## 3️⃣ Efficient Computation (GPU / TPU)

Tensors are optimized for:

- Parallel computation
- GPU acceleration
- Faster training
- Large-scale data processing

PyTorch tensors can move to GPU using:

```
tensor.to("cuda")
```

GPU performs thousands of operations simultaneously → very fast training.

---

# 📍 Where Are Tensors Used?

Tensors are used in every stage of Deep Learning:

---

## 1️⃣ Data Storage

- Input data stored as tensors
- Dataset converted into tensor format
- Images, text, audio all stored as tensors

---

## 2️⃣ Weights and Biases

- Model parameters are tensors
- Each layer has weight tensors
- Bias values are also tensors

Example:
Linear layer weight → 2D tensor

---

## 3️⃣ Matrix Operations

- Forward pass uses matrix multiplication
- Backpropagation uses gradient tensors
- Activation functions operate on tensors

Everything inside model = tensor operations

---

## 4️⃣ Training Process

During training:

1. Input → Tensor
2. Model output → Tensor
3. Loss → Scalar Tensor
4. Gradients → Tensor
5. Weight update → Tensor operation

Training = Continuous tensor computation

---

# 🔥 Final Conclusion

Tensor is used because:

- It stores numerical data
- It performs fast mathematical operations
- It supports GPU acceleration
- It represents real-world data easily
- It is the core structure of Deep Learning

Without tensors → No Deep Learning


In [2]:
import torch # pytorch preinstalled
print(torch.__version__)

2.9.0+cu128


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [4]:
# using empty
a = torch.empty(2,3)
#empty func memeory allocate karta hai

In [6]:
# check type
type(a)
#tensor object

torch.Tensor

In [7]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
# using rand
torch.rand(2,3)

tensor([[0.1324, 0.7211, 0.8475],
        [0.4393, 0.1497, 0.9022]])

In [11]:
# use of seed
# ise hm rand ki value fix karte hai rahegi random hi but change nhi hogi
torch.rand(2,3)

tensor([[0.5024, 0.6389, 0.9597],
        [0.5872, 0.0955, 0.4266]])

In [12]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
# using tensor
#custom tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))
#20 evely and linesrly space value

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [18]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)
#same x ke shape ka tensor ban gya but value alag hogi

tensor([[              0,               0,       189324032],
        [     4294967296,       189241408, 135850229852848]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [31]:
torch.rand_like(x, dtype=torch.float32)
# yaha hm explixityy dtatype like hai beacuse rand flaot nikalta hai and wo equal nhi hoga isliye datstype hm fix karte hai
# and hme batana hoga ki float chahiye

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

## Tensor Data Types

In [27]:
# find data type
x.dtype

torch.int64

In [28]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [29]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [30]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [36]:
x = torch.rand(2,2)
x

tensor([[0.7909, 0.4235],
        [0.0169, 0.2209]])

In [37]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[6.2550e-01, 1.7934e-01],
        [2.8558e-04, 4.8794e-02]])

### 2. Element wise operation

In [38]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.9535, 0.7064, 0.1629],
        [0.8902, 0.5163, 0.0359]])
tensor([[0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])


In [40]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.3059, 0.0204, 0.1629],
        [0.3641, 0.0250, 0.0359]])

In [41]:
c = torch.tensor([1, -2, 3, -4])

In [42]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [43]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [44]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [45]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [46]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [47]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [48]:
# clamp
# ise hm ek range me rakhte hai jisse ye hoga ki sab us range me aa jayenge
# isme hoga ye ki 2 se chote wale sab 2 ban jayenge and 3 se chote wale 3 ban jaynge
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [49]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[8., 9., 7.],
        [9., 2., 6.]])

In [51]:
# sum
#pure matrix ka sum nikal dega ek  baar me
torch.sum(e)
# sum along columns
torch.sum(e, dim=0)
# sum along rows
torch.sum(e, dim=1)

tensor([24., 17.])

In [52]:
# mean
torch.mean(e)
# mean along col
torch.mean(e, dim=0)

tensor([8.5000, 5.5000, 6.5000])

In [53]:
# median
torch.median(e)

tensor(7.)

In [54]:
# max and min
torch.max(e)
torch.min(e)

tensor(2.)

In [55]:
# product
torch.prod(e)

tensor(54432.)

In [56]:
# standard deviation
torch.std(e)

tensor(2.6394)

In [57]:
# variance
torch.var(e)

tensor(6.9667)

In [58]:
# argmax
# sabse  bade wale eleemnts ka position batta hai
torch.argmax(e)

tensor(1)

In [60]:
# argmin
# sabse chota wale(min) eleemnts ka position batta hai
torch.argmin(e)

tensor(4)

### 4. Matrix operations

In [71]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[2, 7, 1],
        [1, 5, 4]])
tensor([[4, 1],
        [1, 2],
        [4, 7]])


In [70]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[87, 51],
        [90, 66]])

In [63]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [64]:
# transpose
torch.transpose(f, 0, 1)

tensor([[7, 3],
        [7, 6],
        [8, 1]])

In [65]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 3., 3.],
        [5., 0., 6.],
        [4., 0., 8.]])

In [75]:
# determinant for sq matrx only
torch.det(h)

tensor(-48.)

In [74]:
# inverse # V for sq matrx onlytorch.inverse(h)

### 5. Comparison operations

In [73]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[2, 5, 6],
        [1, 4, 5]])
tensor([[6, 9, 2],
        [3, 1, 0]])


In [76]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [77]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[2., 1., 2.],
        [7., 9., 2.]])

In [78]:
# log
torch.log(k)

tensor([[0.6931, 0.0000, 0.6931],
        [1.9459, 2.1972, 0.6931]])

In [79]:
# exp
torch.exp(k)

tensor([[7.3891e+00, 2.7183e+00, 7.3891e+00],
        [1.0966e+03, 8.1031e+03, 7.3891e+00]])

In [ ]:
# sqrt
torch.sqrt(k)

tensor([[2.2361, 2.0000, 1.0000],
        [2.6458, 1.0000, 2.8284]])

## 🔹 Sigmoid  
Sigmoid is an activation function that converts any input value into a range between 0 and 1.

## 🔹 ReLU  
ReLU (Rectified Linear Unit) is an activation function that outputs 0 for negative values and keeps positive values unchanged.

## 🔹 Softmax  
Softmax is an activation function that converts multiple values into probability distribution (sum = 1).


In [80]:
# sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.7311, 0.8808],
        [0.9991, 0.9999, 0.8808]])

In [81]:
# softmax
torch.softmax(k, dim=0)

tensor([[6.6929e-03, 3.3535e-04, 5.0000e-01],
        [9.9331e-01, 9.9966e-01, 5.0000e-01]])

In [82]:
# relu
torch.relu(k)

tensor([[2., 1., 2.],
        [7., 9., 2.]])

## Inplace Operations

In [85]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)
# koibhi tensor ka operation ke liye hm ek naya y=tensor banya jata hai

tensor([[0.8993, 0.2732, 0.3397],
        [0.1879, 0.5534, 0.2682]])
tensor([[0.9556, 0.9761, 0.5934],
        [0.3124, 0.9431, 0.8519]])


In [86]:
m.add_(n)
#originally me changs hoga naya nhi bangea

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

In [87]:
m

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

In [88]:
n

tensor([[0.9556, 0.9761, 0.5934],
        [0.3124, 0.9431, 0.8519]])

In [89]:
torch.relu(m) # m me permanaent change nhi hua

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

In [91]:
m.relu_()# m me permanent  chanegs aayega
# underscore batata hai ki inplace operation ho rha hai

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

In [93]:
m

tensor([[1.8549, 1.2494, 0.9331],
        [0.5003, 1.4965, 1.1200]])

## Copying a Tensor

In [94]:
a = torch.rand(2,3)
a

tensor([[0.9815, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [95]:
b = a

In [96]:
b

tensor([[0.9815, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [98]:
a[0][0] = 0

In [99]:
a

tensor([[0.0000, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [100]:
b

tensor([[0.0000, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [101]:
id(a)

135845475786480

In [102]:
id(b)
# IT MEANS # a and b safe jaagah ka refrence pass hua hai

135845475786480

In [104]:
b = a.clone()

In [106]:
a

tensor([[0.0000, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [105]:
b

tensor([[0.0000, 0.1132, 0.4783],
        [0.4436, 0.3847, 0.4521]])

In [107]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.9985,  0.6783],
        [ 0.2776,  0.6227,  0.2982]])

In [ ]:
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
id(a)

134838567488544

In [ ]:
id(b)
#clone karte hi nhi memroy me naya tensor banta hai

134838569581552

# Tensor Operations on GPU

In [108]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

In [109]:
device=torch.device('cuda')

In [111]:
#creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938]], device='cuda:0')

In [113]:
#moving an existing tensor  to GPU
a

tensor([[10.0000,  0.1132,  0.4783],
        [ 0.4436,  0.3847,  0.4521]])

In [114]:
b=a.to(device)

tensor([[10.0000,  0.1132,  0.4783],
        [ 0.4436,  0.3847,  0.4521]], device='cuda:0')

In [115]:
b+5

tensor([[5.0000, 5.1132, 5.4783],
        [5.4436, 5.3847, 5.4521]])