<a href="https://colab.research.google.com/github/Ramandeep-Singh17/DLusingPyTorch/blob/main/5part2_dataset_and_dataloader_demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🔥 Recap + Why Dataset & DataLoader Needed

---

# 🔹 🔁 Recap (Flow till now)

1. Tensors → Data ko numerical form me store kiya  
2. Autograd → Automatic gradients (derivatives)  
3. nn Module → Neural network easily build kiya  
4. Training Pipeline → forward → loss → backward → update  

---

# 🔹 Abhi hum kya kar rahe the?

Hum **Batch Gradient Descent** use kar rahe the:

👉 Pure dataset ek saath use karke update

---

## ❌ Problem with Batch Gradient Descent

1. Memory inefficient  
   → Large dataset RAM/GPU me fit nahi hota  

2. Slow convergence  
   → Har update ke liye poora data use ho raha hai (slow learning)

---

# 🔹 Solution → Mini-Batch Gradient Descent

👉 Data ko chhote batches me tod dete hain

Example:
1000 rows → batch size = 100  
→ 10 batches  

Ab:
- Har batch ke baad update  
- Faster + efficient  

---

# 🔹 Tumne kya kiya (Manual Mini-Batch Code)

Tumne manually:

- start_idx, end_idx use kiya  
- slicing se batch banaya  
- loop chalaya  

✔ Concept correct hai  
❌ But scalable nahi hai  

---

# 🔴 Problems with Manual Approach

## 1. No Standard Interface for Data

Har baar:
- alag tareeke se data load karna padta hai  
- koi fixed structure nahi  

👉 Messy code

---

## 2. No Easy Way to Apply Transformations

Real-world me:

- image resize karna
- normalization
- augmentation

Manual code me:
❌ Hard to manage

---

## 3. Shuffling & Sampling Problem

Training me:

- data shuffle hona chahiye
- random sampling hona chahiye

Manual me:
❌ khud likhna padega (error-prone)

---

## 4. Batch Management & Parallelization

- batch banana manually
- multi-core loading nahi
- slow data pipeline

👉 Large scale DL me fail ho jayega

---

# ❌ Final Problem

👉 Ye approach scalable nahi hai  
👉 Real-world deep learning me use nahi hota  

---

# 🔥 Solution → Dataset + DataLoader

In sab problems ko solve karne ke liye:

👉 PyTorch deta hai:

- Dataset → data ko structure deta hai  
- DataLoader → batching, shuffle, fast loading  

---

# 🔥 Hinglish Final Understanding

Batch gradient descent slow aur memory heavy tha  
isliye hum mini-batch use kar rahe hain  

Par manual batching scalable nahi hai  
isliye PyTorch me Dataset aur DataLoader use karte hain  
jo data handling ko easy, fast aur professional bana deta hai


**Next part**

In [1]:
from sklearn.datasets import make_classification
import torch

# 🔥 Dataset & DataLoader (PyTorch)

---

## 🔹 Dataset Kya Hai?

Dataset ek **blueprint / structure** hai  
jo batata hai:

👉 Data kaha hai  
👉 Data kaise load hoga  
👉 Data kaise return hoga  

---

## 🔹 Dataset = Abstract Class

- Direct use nahi karte  
- Apni custom class banate hain  

---

## 🔹 Dataset ke 3 Important Methods

### 1. __init__()
👉 Data load kaise hoga

Example:
- CSV read
- images load
- arrays store

---

### 2. __len__()
👉 Total samples batata hai (NOT batches)

Example:
1000 rows → len = 1000

---

### 3. __getitem__(index)
👉 Kisi bhi index ka data return karta hai

Example:
dataset[5] → (x, y)

---

## 🔥 Example Samajh

Data:
[ (2,0), (5,1), (7,0), (9,1) ]

- len() → 4  
- getitem(2) → (7,0)

---

# 🔥 DataLoader Kya Hai?

DataLoader = Dataset ka helper

👉 Data ko:
- Batch me convert karta hai  
- Shuffle karta hai  
- Fast loading karta hai  

---

## 🔹 DataLoader Flow (Step-by-Step)

Maan lo:

data = [0,1,2,3,4,5,6,7,8,9]  
batch_size = 2  
shuffle = True  

---

### Step 1: Shuffle (Sampler)

Original:
0 1 2 3 4 5 6 7 8 9  

Shuffled:
4 6 1 3 7 8 2 0 9 5  

---

### Step 2: Batches me divide

[4,6]  
[1,3]  
[7,8]  
[2,0]  
[9,5]  

---

### Step 3: Dataset se data fetch

dataset[4], dataset[6] → batch  

---

### Step 4: Combine (collate_fn)

👉 Batch ready  

---

### Step 5: Training loop me use

for batch in dataloader:
    model(batch)

---

# 🔴 Important Points

- Dataset → data ka source  
- DataLoader → data ka manager  
- len() → total samples (NOT batches)  
- Shuffling → DataLoader karta hai  
- Batching → DataLoader karta hai  

---

# 🔥 Final Hinglish Understanding

Dataset batata hai data kaha se aur kaise aayega  
DataLoader us data ko shuffle karke batches me model tak pahunchata hai  

👉 Dataset = "data dene wala"  
👉 DataLoader = "data manage karne wala"


In [2]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [3]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [4]:
X.shape

(10, 2)

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
y.shape
#target col

(10,)

In [7]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [8]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [9]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [10]:
from torch.utils.data import Dataset, DataLoader

In [11]:
class CustomDataset(Dataset):
  #inherit from dataset

  def __init__(self, features, labels):

    self.features = features
    self.labels = labels

  def __len__(self):

    return self.features.shape[0]

  def __getitem__(self, index):

    return self.features[index], self.labels[index]

In [12]:
dataset = CustomDataset(X, y)

In [13]:
len(dataset)

10

In [14]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [24]:
dataloader = DataLoader(dataset, batch_size=2, shuffle=False)
#shuffle true karne se randomly ban a hai and agar false karenge tab order me batches banenge  2 points ko mila ke 1st wala banega

In [27]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------


**📦 1. Transformations (Dataset me kaise use hote hain)**

# 🔥 Transformations in Dataset

---

## 🔹 Problem (Manual Approach)

Manual batching me:
- Image resize
- Normalization
- Augmentation

ye sab karna mushkil hota hai ❌

---

## 🔹 Solution (Dataset me)

Dataset ke `__getitem__()` me hi transformation likh dete hain

Example:
```
def __getitem__(self, index):
    x = self.X[index]
    y = self.y[index]

    x = transform(x)   # yaha transformation

    return x, y
```

---

## 🔥 Hinglish Samajh

Manual code me transformation manage karna tough tha  
But Dataset me `getitem` ke andar likh do → automatically har sample pe apply ho jayega


**⚡ 2. Parallelization (num_workers)**

---
# 🔥 Parallel Data Loading (num_workers)

---

## 🔹 Problem

Abhi tak:
👉 Data sequential load ho raha tha  
👉 Slow training ❌

---

## 🔹 Solution

Use:
```
DataLoader(..., num_workers=4)
```

---

## 🔹 Kaise kaam karta hai?

- Multiple workers (CPU processes) ban jate hain
- Har worker alag batch load karta hai

Example:

Worker 1 → Batch 1  
Worker 2 → Batch 2  
Worker 3 → Batch 3  
Worker 4 → Batch 4  

👉 Parallel loading = faster training 🚀

---

## 🔥 Hinglish Samajh

Pehle ek hi banda data load kar raha tha (slow)  
Ab 4 bande ek saath kaam kar rahe hain (fast)



**🎲 3. Sampler (Shuffle & Custom Sampling)**

# 🔥 Sampler in DataLoader

---

## 🔹 What is Sampler?

Sampler decide karta hai:
👉 Data kis order me aayega

---

## 🔹 Types

### 1. SequentialSampler
- Order same rehta hai
- shuffle=False

Example:
0 1 2 3 4 5 ...

---

### 2. RandomSampler
- Data random order me aata hai
- shuffle=True

Example:
4 1 7 2 0 5 ...

---

## 🔹 Why Shuffle?

- Model overfit na kare order pe
- Better learning

---

## 🔹 Custom Sampler (Important)

Use case:
👉 Imbalanced dataset

Example:
- Class A → 99%
- Class B → 1%

Problem:
Model biased ho jayega ❌

---

## 🔹 Solution

Custom sampler use karke:
👉 Rare class ko zyada sample kara sakte hain

---

## 🔥 Hinglish Samajh

Sampler decide karta hai data ka order  
Shuffle=True → random learning  
Custom sampler → imbalance problem solve


**🧩 4. collate_fn (Batch banane ka logic)**

# 🔥 collate_fn in DataLoader

---

## 🔹 What is collate_fn?

collate_fn decide karta hai:
👉 Multiple samples ko combine karke batch kaise banega

---

## 🔹 Default Behavior

- Simply stack karta hai tensors

---

## 🔹 Problem

Text data:

[1,2,3]  
[4,5]  
[6,7,8,9]  

👉 Length different ❌

---

## 🔹 Solution → Padding

```
[1,2,3,0]  
[4,5,0,0]  
[6,7,8,9]
```

👉 Same length bana diya

---

## 🔹 Custom collate_fn

- Padding
- Custom batching
- Complex data handle

---

## 🔥 Hinglish Samajh

collate_fn batch banata hai  
Agar data unequal ho → padding use karke equal karta hai


**⚙️ 5. Important Parameters of DataLoader**

# 🔥 DataLoader Important Parameters

---

## 1️⃣ dataset (mandatory)

- Data source
- Custom Dataset hona chahiye

---

## 2️⃣ batch_size

- Kitne samples ek batch me

Example:
batch_size = 32

---

## 3️⃣ shuffle

- True → data random
- False → sequential

---

## 4️⃣ num_workers

- Parallel loading

Example:
num_workers=4 → 4 workers

---

## 5️⃣ pin_memory

- GPU transfer fast karta hai

Used when:
CUDA (GPU) use ho raha ho

---

## 6️⃣ drop_last
#genrally drop last ko false rakhte hai taki last wala remove na ho but last wala remove karne se wo hat jata hai

- Last incomplete batch drop karta hai

Example:
100 samples, batch=32  
→ last 4 drop ho jayenge

---

## 7️⃣ collate_fn

- Custom batch logic
- Padding, etc.

---

## 8️⃣ sampler

- Custom sampling strategy

---

# 🔥 Final Hinglish Summary

Dataset → data deta hai  
DataLoader → batching, shuffle, speed handle karta hai  

Ye sab milke deep learning pipeline ko scalable banate hain 🚀
